name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.2' }
      - run: sudo apt-get update && sudo apt-get install -y yamllint
      - run: yamllint -s Codex
